# Prometheus Configuration for AOC V2 Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MongoDB monitoring
  - job_name: 'mongodb'
    static_configs:
      - targets: ['samserver-mongodb:27017']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['samserver-redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['samserver-images:80']
    scrape_interval: 30s
    metrics_path: /nginx_status

  # Docker container monitoring
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
