exports.ENG = {
    "SPEED" : "Speed",
    "PUSH_TITLE":{
        "AMBULANCE_SPEED_WARNING": "AMBULANCE_SPEED_WARNING",
        "AMBULANCE_SPEED_ALERT": "AMBULANCE_SPEED_ALERT",
        "AMBULANCE_SPEED_NORMAL": "AMBULANCE_SPEED_NORMAL",
        "OPERATION_STATUS_CHANGE": "OPERATION_STATUS_CHANGE",
        "AMBULACNE_NEAR_SCENE" : "AMBULACNE_NEAR_SCENE",
        "AMBULANCE_STATUS" : "AMBULANCE_STATUS",
        "CRASH_NOTIFY": "CRASH_NOTIFY",
        "ALIVE_REQ_CREATE": "ALIVE_REQ_CREATE",
    },

    "SPEED_ABOVE_80": "SPEED_ABOVE_80",
    "SPEED_BELOW_80": "SPEED_BELOW_80",
    "SPEED_ABOVE_120": "SPEED_ABOVE_120",
    "SPEED_BELOW_120": "SPEED_BELOW_120",

    // "CRASH_NOTIFY": "CRASH_NOTIFY",

    "AMBULACNE_NEAR_ABOUT_SCENE": "AMBULACNE_NEAR_ABOUT_SCENE",

    "AMBULANCE_TRACKING_STATUS_ONLINE": "AMBULANCE_TRACKING_STATUS_ONLINE",
    "AMBULANCE_TRACKING_STATUS_OFFLINE": "AMBULANCE_TRACKING_STATUS_OFFLINE",

    "PATIENT_MONITOR_STATUS_ONLINE": "PATIENT_MONITOR_STATUS_ONLINE",
    "PATIENT_MONITOR_STATUS_OFFLINE": "PATIENT_MONITOR_STATUS_OFFLINE",

    "GLASS_MACS_STATUS_ONLINE": "GLASS_MACS_STATUS_ONLINE",
    "GLASS_MACS_STATUS_OFFLINE": "GLASS_MACS_STATUS_OFFLINE",

    "OPERATION_STATUS_OPERATION_ASSIGNED": "OPERATION_STATUS_OPERATION_ASSIGNED",
    "OPERATION_STATUS_START_OPERATION": "OPERATION_STATUS_START_OPERATION",
    "OPERATION_STATUS_DEPART_FROM_BASE_HOSPITAL": "OPERATION_STATUS_DEPART_FROM_BASE_HOSPITAL",
    "OPERATION_STATUS_ARRIVAL_AT_SCENE": "OPERATION_STATUS_ARRIVAL_AT_SCENE",
    "OPERATION_STATUS_DEPART_FROM_SCENE": "OPERATION_STATUS_DEPART_FROM_SCENE",
    "OPERATION_STATUS_GO_TO_BASE_HOSPITAL": "OPERATION_STATUS_GO_TO_BASE_HOSPITAL",
    "OPERATION_STATUS_ARRIVAL_AT_BASE_HOSPITAL": "OPERATION_STATUS_ARRIVAL_AT_BASE_HOSPITAL",
    "OPERATION_STATUS_GO_TO_ANOTHER_HOSPITAL": "OPERATION_STATUS_GO_TO_ANOTHER_HOSPITAL",
    "OPERATION_STATUS_ARRIVAL_AT_ANOTHER_HOSPITAL": "OPERATION_STATUS_ARRIVAL_AT_ANOTHER_HOSPITAL",
    "OPERATION_STATUS_GO_BACK_TO_BASE_HOSPITAL": "OPERATION_STATUS_GO_BACK_TO_BASE_HOSPITAL",
    "OPERATION_STATUS_COME_BACK_TO_BASE_HOSPITAL": "OPERATION_STATUS_COME_BACK_TO_BASE_HOSPITAL",
    "OPERATION_STATUS_COMPLETED": "OPERATION_STATUS_COMPLETED",
    "OPERATION_STATUS_CANCELED": "OPERATION_STATUS_CANCELED",
    "OPERATION_STATUS_IDEAL": "OPERATION_STATUS_IDEAL",
}


exports.THAI = {
    "SPEED" : "Speed_thai",

    "PUSH_TITLE":{
        "AMBULANCE_SPEED_WARNING": "AMBULANCE_SPEED_WARNING_thai",
        "AMBULANCE_SPEED_ALERT": "AMBULANCE_SPEED_ALERT_thai",
        "AMBULANCE_SPEED_NORMAL": "AMBULANCE_SPEED_NORMAL_thai",
        "OPERATION_STATUS_CHANGE": "OPERATION_STATUS_CHANGE_thai",
        "AMBULACNE_NEAR_SCENE" : "AMBULACNE_NEAR_SCENE_thai",
        "AMBULACNE_STATUS" : "AMBULACNE_STATUS_thai",
        "CRASH_NOTIFY": "CRASH_NOTIFY_thai",
        "ALIVE_REQ_CREATE": "ALIVE_REQ_CREATE_thai"
    },
    

    "SPEED_ABOVE_80": "SPEED_ABOVE_80_thai",
    "SPEED_BELOW_80": "SPEED_BELOW_80_thai",
    "SPEED_ABOVE_120": "SPEED_ABOVE_120_thai",
    "SPEED_BELOW_120": "SPEED_BELOW_120_thai",

    // "CRASH_NOTIFY": "CRASH_NOTIFY_thai",

    "AMBULACNE_NEAR_ABOUT_SCENE": "AMBULACNE_NEAR_ABOUT_SCENE_thai",

    "AMBULANCE_TRACKING_STATUS_ONLINE": "AMBULANCE_TRACKING_STATUS_ONLINE_thai",
    "AMBULANCE_TRACKING_STATUS_OFFLINE": "AMBULANCE_TRACKING_STATUS_OFFLINE_thai",

    "PATIENT_MONITOR_STATUS_ONLINE": "PATIENT_MONITOR_STATUS_ONLINE_thai",
    "PATIENT_MONITOR_STATUS_OFFLINE": "PATIENT_MONITOR_STATUS_OFFLINE_thai",

    "GLASS_MACS_STATUS_ONLINE": "GLASS_MACS_STATUS_ONLINE_thai",
    "GLASS_MACS_STATUS_OFFLINE": "GLASS_MACS_STATUS_OFFLINE_thai",

    "OPERATION_STATUS_OPERATION_ASSIGNED": "OPERATION_STATUS_OPERATION_ASSIGNED_thai",
    "OPERATION_STATUS_START_OPERATION": "OPERATION_STATUS_START_OPERATION_thai",
    "OPERATION_STATUS_DEPART_FROM_BASE_HOSPITAL": "OPERATION_STATUS_DEPART_FROM_BASE_HOSPITAL_thai",
    "OPERATION_STATUS_ARRIVAL_AT_SCENE": "OPERATION_STATUS_ARRIVAL_AT_SCENE_thai",
    "OPERATION_STATUS_DEPART_FROM_SCENE": "OPERATION_STATUS_DEPART_FROM_SCENE_thai",
    "OPERATION_STATUS_GO_TO_BASE_HOSPITAL": "OPERATION_STATUS_GO_TO_BASE_HOSPITAL_thai",
    "OPERATION_STATUS_ARRIVAL_AT_BASE_HOSPITAL": "OPERATION_STATUS_ARRIVAL_AT_BASE_HOSPITAL_thai",
    "OPERATION_STATUS_GO_TO_ANOTHER_HOSPITAL": "OPERATION_STATUS_GO_TO_ANOTHER_HOSPITAL_thai",
    "OPERATION_STATUS_ARRIVAL_AT_ANOTHER_HOSPITAL": "OPERATION_STATUS_ARRIVAL_AT_ANOTHER_HOSPITAL_thai",
    "OPERATION_STATUS_GO_BACK_TO_BASE_HOSPITAL": "OPERATION_STATUS_GO_BACK_TO_BASE_HOSPITAL_thai",
    "OPERATION_STATUS_COME_BACK_TO_BASE_HOSPITAL": "OPERATION_STATUS_COME_BACK_TO_BASE_HOSPITAL_thai",
    "OPERATION_STATUS_COMPLETED": "OPERATION_STATUS_COMPLETED_thai",
    "OPERATION_STATUS_CANCELED": "OPERATION_STATUS_CANCELED_thai",
    "OPERATION_STATUS_IDEAL": "OPERATION_STATUS_IDEAL_thai",
}